name: CI-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: unit testing
    runs-on: windows-2019

    steps:
      - name: Checkout simple_functions
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
        shell: cmd

      - name: Test with pytest
        run: |
          python -m pytest tests/
        shell: cmd



